"""Regression tests for the approved-stub check."""
import contextlib
import importlib.util
import io
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location('stub_check', ROOT / 'scripts/doc-control/stub_check.py')
stubs = importlib.util.module_from_spec(spec)
spec.loader.exec_module(stubs)

STUB = ('---\nid: TEST-001\nstatus: approved\nauto_generated: false\n---\n'
        '# 06 Design\n\n**Purpose:** Component Design.\n'
        '**Automation Rule:** Files here should be auto-linked to the inventory.\n')
REAL = ('---\nid: TEST-002\nstatus: approved\nauto_generated: false\n---\n'
        '# Design\n\n## Purpose and scope\n\nThis document states why the design applies'
        ' and what is out of scope for the sample service.\n')


class StubCheckTests(unittest.TestCase):
    def write(self, folder, name, text):
        path = Path(folder) / 'docs' / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        return path

    def test_substance_ignores_index_boilerplate(self):
        self.assertEqual(stubs.substance(STUB), (0, 0))

    def test_substance_counts_sections_and_content(self):
        sections, words = stubs.substance(REAL)
        self.assertEqual(sections, 1)
        self.assertGreater(words, 10)

    def test_substance_rejects_placeholders_and_generated_marker(self):
        text = ('<!-- AUTO-GENERATED BY AUTODOC ENGINE. DO NOT EDIT. SOURCE: x -->\n'
                '---\nid: TEST-003\nstatus: approved\nauto_generated: true\n---\n'
                '# Title\n\n## Section\n\n<!-- Fill in. -->\n')
        self.assertEqual(stubs.substance(text), (1, 0))

    def test_approved_stub_fails_and_draft_stub_only_warns(self):
        with tempfile.TemporaryDirectory() as folder:
            stub = self.write(folder, 'stub.md', STUB)
            with patch.object(stubs, 'ROOT', Path(folder)), \
                    patch.object(stubs, 'controlled', return_value=[stub]):
                captured = io.StringIO()
                with contextlib.redirect_stderr(captured):
                    self.assertFalse(stubs.check())
                self.assertIn('approved document has no section', captured.getvalue())
            draft = self.write(folder, 'draft.md', STUB.replace('status: approved', 'status: draft'))
            with patch.object(stubs, 'ROOT', Path(folder)), \
                    patch.object(stubs, 'controlled', return_value=[draft]):
                captured = io.StringIO()
                with contextlib.redirect_stderr(captured):
                    self.assertTrue(stubs.check())
                self.assertIn('WARNING:', captured.getvalue())

    def test_generated_documents_are_excluded(self):
        generated = ('<!-- AUTO-GENERATED BY AUTODOC ENGINE. DO NOT EDIT. SOURCE: x -->\n'
                     '---\nid: TEST-004\nstatus: approved\nauto_generated: true\n---\n'
                     '# Title\n\n## Section\n')
        with tempfile.TemporaryDirectory() as folder:
            path = self.write(folder, 'generated.md', generated)
            with patch.object(stubs, 'ROOT', Path(folder)), \
                    patch.object(stubs, 'controlled', return_value=[path]):
                with contextlib.redirect_stderr(io.StringIO()):
                    self.assertTrue(stubs.check())

    def test_repository_has_no_approved_stubs(self):
        approved, _ = stubs.scan()
        self.assertEqual(approved, [], 'approved title-only documents: ' + ', '.join(approved))


if __name__ == '__main__':
    unittest.main()
