"""Tests for §6: per-language generators, their exactness labels and their sandboxed runner."""
import importlib.util
import json
import os
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def load_module(name, relative):
    spec = importlib.util.spec_from_file_location(name, ROOT / relative)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


engine = load_module('autodoc_engine', 'scripts/doc-sync/engine.py')
languages = load_module('autodoc_languages', 'scripts/doc-sync/languages.py')

TOOLCHAINS = ROOT / 'tests/fixtures/toolchains'
GO_SERVICE = ROOT / 'tests/fixtures/repos/go-service'
GO_FILES = sorted(str(path) for path in GO_SERVICE.rglob('*.go'))


def path_with(toolchain):
    return os.pathsep.join([str(TOOLCHAINS / toolchain), os.environ.get('PATH', '')])


class GeneratorLabelTests(unittest.TestCase):
    """Every generator states how exact it is, in the same shape the fact detectors use."""

    def test_every_generator_declares_exactness_and_limits(self):
        self.assertEqual(set(engine.GENERATORS), set(engine.GENERATOR_LABELS),
                         'a generator without a label, or a label for a generator that is gone')
        for name, label in engine.GENERATOR_LABELS.items():
            with self.subTest(name):
                self.assertIn(label['exactness'], ('exact', 'heuristic'))
                self.assertTrue(label['limits'].strip(), 'a label without limits is a claim')

    def test_every_generated_markdown_target_carries_its_label(self):
        for entry in engine.load_map()['generated']:
            target = ROOT / entry['target']
            if target.suffix != '.md':
                continue
            label = engine.GENERATOR_LABELS[entry['generator']]
            marker = target.read_text(encoding='utf-8').splitlines()[0]
            with self.subTest(entry['id']):
                self.assertTrue(marker.startswith('<!-- AUTO-GENERATED BY AUTODOC ENGINE.'))
                self.assertIn(f'GENERATOR: {entry["generator"]} | ', marker)
                self.assertIn(f'EXACTNESS: {label["exactness"]} | ', marker)
                self.assertIn(f'LIMITS: {label["limits"]} | SOURCE:', marker)

    def test_heuristic_generators_warn_by_default_and_exact_ones_do_not(self):
        findings = []
        engine.generate(check=True, findings=findings)
        labelled = {entry['generator']: entry['target'] for entry in engine.load_map()['generated']}
        heuristic = {name for name, label in engine.GENERATOR_LABELS.items()
                     if label['exactness'] == 'heuristic'}
        warned = [finding for finding in findings if finding['rule'] == 'generator.heuristic']
        self.assertEqual({finding['location'] for finding in warned},
                         {labelled[name] for name in heuristic},
                         'one advisory finding per heuristic target, and none for exact ones')
        for finding in warned:
            generator = finding['detail'].split('`')[1]
            self.assertIn(engine.GENERATOR_LABELS[generator]['limits'], finding['detail'],
                          'the warning carries the limits a reader needs to judge the output')


class LanguageRunnerTests(unittest.TestCase):
    """The runner integrates a tool; it never reimplements one and never fakes output."""

    def test_the_command_prints_an_external_reference_and_writes_nothing(self):
        before = {str(target): (ROOT / target).read_bytes()
                  for entry in engine.load_map()['generated'] for target in [entry['target']]}
        proc = __import__('subprocess').run(
            [__import__('sys').executable, str(ROOT / 'scripts/doc-sync/languages.py'),
             '--show', 'go', '--repo', str(GO_SERVICE)],
            capture_output=True, text=True, cwd=ROOT,
            env={**os.environ, 'PATH': path_with('good')})
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertIn('func Add(a int, b int) int', proc.stdout,
                      'the toolchain\'s own output is the reference — verbatim, not summarized')
        after = {str(target): (ROOT / target).read_bytes()
                 for entry in engine.load_map()['generated'] for target in [entry['target']]}
        self.assertEqual(before, after,
                         'an environment-dependent reference is printed, never committed')

    def test_python_is_extracted_in_process_and_deterministically(self):
        files = [ROOT / 'scripts/doc-sync/languages.py', ROOT / 'engine/extractors/facts.py']
        first = languages.run('python', ROOT, files=files)
        second = languages.run('python', ROOT, files=files)
        self.assertEqual(first['status'], 'generated')
        self.assertEqual(first['exactness'], 'exact')
        self.assertEqual(first['text'], second['text'], 'in-process output must be reproducible')
        self.assertIn('## Python declarations (exact, in-process)', first['text'])
        self.assertIn('`available`', first['text'])

    def test_the_tool_runs_inside_the_repository_with_a_scrubbed_offline_environment(self):
        os.environ['AWS_SECRET_ACCESS_KEY'] = 'fixture-secret-value'
        self.addCleanup(os.environ.pop, 'AWS_SECRET_ACCESS_KEY', None)
        result = languages.run('go', GO_SERVICE, files=GO_FILES, path=path_with('good'))
        self.assertEqual(result['status'], 'generated')
        self.assertIn(f'cwd: {GO_SERVICE.resolve()}', result['text'], 'the tool runs in the repo')
        self.assertIn('args: doc -all .', result['text'])
        self.assertIn('GOPROXY=off GOFLAGS=-mod=readonly GOTOOLCHAIN=local', result['text'],
                      'the toolchain is told to stay offline, and never to fetch a toolchain')
        self.assertIn('secret: not passed', result['text'],
                      'the caller environment is never inherited')
        self.assertNotIn('fixture-secret-value', result['text'])

    def test_a_missing_tool_is_unavailable_with_its_name_never_replaced(self):
        result = languages.run('go', GO_SERVICE, files=GO_FILES, path='/nonexistent-autodoc')
        self.assertEqual(result['status'], 'unavailable')
        self.assertIn('`go` is not on PATH', result['reason'])
        self.assertIsNone(result['text'])

    def test_nothing_to_read_is_stated_instead_of_running_the_tool(self):
        result = languages.run('go', GO_SERVICE, files=[], path=path_with('good'))
        self.assertEqual(result['status'], 'no-files')
        self.assertIsNone(result['text'])

    def test_a_failing_tool_reports_its_exit_and_stderr_tail(self):
        result = languages.run('go', GO_SERVICE, files=GO_FILES, path=path_with('failing'))
        self.assertEqual(result['status'], 'failed')
        self.assertIn('exited 7', result['reason'])
        self.assertIn('no go.mod found', result['reason'])
        self.assertIsNone(result['text'])

    def test_a_hanging_tool_is_stopped_by_the_timeout(self):
        result = languages.run('go', GO_SERVICE, files=GO_FILES, path=path_with('slow'), timeout=1)
        self.assertEqual(result['status'], 'timed_out')
        self.assertIn('within 1s', result['reason'])
        self.assertIsNone(result['text'])

    def test_a_language_without_a_generator_is_l0_and_says_why(self):
        result = languages.run('ruby', GO_SERVICE, files=GO_FILES)
        self.assertEqual(result['status'], 'unavailable')
        self.assertIn('No generator is declared', result['reason'])
        self.assertIn('L0', result['limits'])


class LanguageCoverageTests(unittest.TestCase):
    """Reports state what each code language gets, so no language is silently unread."""

    def test_rows_state_l0_for_a_language_with_no_generator(self):
        rows = languages.rows({'python': 4, 'javascript': 2, 'markdown': 9, 'sql': 1})
        self.assertEqual([row['language'] for row in rows], ['javascript', 'python', 'sql'],
                         'only code languages are reported; prose and data formats are not')
        javascript = rows[0]
        self.assertIsNone(javascript['generator'])
        self.assertIsNone(javascript['exactness'])
        self.assertIn('L0', javascript['limits'])
        self.assertEqual(rows[1]['generator'], 'python')
        self.assertEqual(rows[1]['exactness'], 'exact')

    def test_the_line_names_a_declared_generator_that_cannot_run_here(self):
        rows = languages.rows({'go': 2, 'python': 1}, path='/nonexistent-autodoc', probe=True)
        line = languages.line(rows)
        self.assertIn('python (exact via ast (the CPython parser))', line)
        self.assertIn('go (declared exact via go doc -all .', line)
        self.assertIn('`go` is not on PATH', line)
        self.assertIn('L0 in this run', line)

    def test_test_inputs_are_not_counted_as_project_languages(self):
        counts = languages.declarations(languages.tracked_language_files(ROOT), ROOT)
        self.assertNotIn('go', counts,
                         'fixture toolchains are evidence about AutoDOC, not code of this project')

    def test_the_command_never_crashes_on_a_tool_that_is_missing(self):
        proc = __import__('subprocess').run(
            [__import__('sys').executable, str(ROOT / 'scripts/doc-sync/languages.py'),
             '--show', 'go'],
            capture_output=True, text=True, cwd=ROOT,
            env={**os.environ, 'PATH': '/nonexistent-autodoc'})
        self.assertEqual(proc.returncode, 1, 'an unavailable tool is a stated failure, not a crash')
        self.assertIn('`go` is not on PATH', proc.stderr)
        self.assertNotIn('Traceback', proc.stderr)

    def test_the_committed_inventory_states_the_language_situation(self):
        text = (ROOT / 'docs/META/CODE-INVENTORY.md').read_text(encoding='utf-8')
        self.assertIn('## Languages in these sources', text)
        javascript = next(line for line in text.splitlines() if line.startswith('| javascript |'))
        self.assertIn('| L0 |', javascript)
        self.assertIn('## Python declarations (exact, in-process)', text)
        self.assertIn('definitions created at runtime, generated code and non-module sources',
                      text)


if __name__ == '__main__':
    unittest.main()
