"""AutoDOC sync engine. JSON is used as a dependency-free subset of YAML for the map."""
import argparse
import hashlib
import fnmatch
import json
import re
import subprocess
import sys
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "engine"))
from extractors.env_alerts import environment, alerts
from extractors.local_policy import tool_matrix
from extractors.facts import headings, python_symbols, python_tests, python_dependencies, sqlite_tables, demo_routes, config_properties
MAP = ROOT / 'docs/.doc-sync-map.yaml'


def safe_path(value):
    path = Path(value)
    if path.is_absolute() or '..' in path.parts or not (ROOT / path).resolve().is_relative_to(ROOT):
        raise ValueError('Target must be inside the repository: ' + value)
    return ROOT / path


def load_map():
    if not MAP.is_file():
        # No declared generators, so drift has nothing to compare here. A repository that has not
        # adopted generated documents has no drift, which is different from a broken generator.
        return {'version': 1, 'generated': []}
    data = json.loads(MAP.read_text(encoding='utf-8'))
    if data.get('version') != 1:
        raise ValueError('Unsupported sync map version')
    ids, targets = set(), set()
    for entry in data['generated']:
        if entry['id'] in ids or entry['target'] in targets:
            raise ValueError('Duplicate generator id/target')
        ids.add(entry['id'])
        targets.add(entry['target'])
        safe_path(entry['target'])
        if entry['generator'] not in GENERATORS:
            raise ValueError('Unknown generator: ' + entry['generator'])
        for source in entry['sources']:
            if Path(source).is_absolute() or '..' in Path(source).parts:
                raise ValueError('Source must be inside the repository: ' + source)
            matches_ = [p for p in ROOT.glob(source) if p.is_file()]
            if not matches_:
                raise ValueError('Missing source files: ' + source + '; fix docs/.doc-sync-map.yaml')
            if any(not p.resolve().is_relative_to(ROOT.resolve()) for p in matches_):
                raise ValueError('Source escapes repository: ' + source)
    return data


def paths(entry):
    return sorted({p for pattern in entry['sources'] for p in ROOT.glob(pattern) if p.is_file()})


def header(doc_id, title, source):
    # Generated content is deterministic: no timestamp of the build or machine paths.
    return (f'<!-- AUTO-GENERATED BY AUTODOC ENGINE. DO NOT EDIT MANUALLY. SOURCE: {source} -->\n'
            f'---\nid: {doc_id}\ntitle: {title}\ntype: REF\nowner: "@Er-Sajan-PLG"\n'
            'reviewer: "@Er-Sajan-PLG"\nclassification: public\nstatus: approved\nversion: "1.0"\n'
            'effective_date: 2026-09-26\nnext_review: 2099-01-01\nsource_of_truth: '
            f'{source}\nsupersedes: null\nrelated: []\ncriticality: low\nreview_days: 365\n'
            'last_verified: 2026-09-26\nlast_reviewed: 2026-09-26\nlast_updated: 2026-09-26\n'
            'auto_generated: true\n---\n\n')


def api(entry):
    routes = demo_routes(paths(entry)[0])
    lines = [header('EX-API-001', 'Task API reference', entry['sources'][0]), '# Task API reference', '',
             'Generated from the route registry. The server dispatches only registered routes.', '',
             '| Method | Path | Purpose | Response |', '| --- | --- | --- | --- |']
    for r in routes:
        lines.append(f"| {r['method']} | `{r['path']}` | {r['description']} | {r['response']} |")
    return '\n'.join(lines) + '\n'


def config(entry):
    properties = config_properties(paths(entry)[0])
    lines = [header('EX-CFG-001', 'Configuration reference', entry['sources'][0]), '# Configuration reference', '',
             '| Variable | Type | Default | Purpose |', '| --- | --- | --- | --- |']
    for name, field in properties.items():
        lines.append(f"| `{name}` | {field['type']} | `{field['default']}` | {field['description']} |")
    return '\n'.join(lines) + '\n'


def env(entry):
    properties = config_properties(paths(entry)[0])
    return '# Generated from config.schema.json; do not edit.\n' + ''.join(
        f"# {v['description']}\n{k}={v['default']}\n" for k, v in properties.items())


def sql(entry):
    tables = sqlite_tables(paths(entry)[0])
    lines = [header('EX-DATA-001', 'Data dictionary', entry['sources'][0]), '# Data dictionary', '',
             'Generated from the supported SQLite CREATE TABLE subset. Unsupported DDL fails generation.', '']
    for table, fields in tables:
        lines.extend([f'## {table}', '', '| Field | Definition |', '| --- | --- |'])
        for name, definition in fields:
            lines.append(f'| `{name}` | {definition} |')
        lines.append('')
    return '\n'.join(lines) + '\n'


def automation(entry):
    lines = [header('DOC-AUTO-001', 'Automation reference', 'docs/.doc-sync-map.yaml'),
             '# Automation reference', '', 'Generated inventory of the sync engine and mapped source files.', '',
             '## Mappings', '', '| ID | Generator | Sources | Target |', '| --- | --- | --- | --- |']
    for item in load_map()['generated']:
        lines.append(f"| {item['id']} | {item['generator']} | {', '.join(item['sources'])} | {item['target']} |")
    lines.extend(['', '## Scripts', ''])
    for path in paths(entry):
        if path.suffix == '.py':
            lines.append(f'- `{path.relative_to(ROOT)}`')
    return '\n'.join(lines) + '\n'



def catalog(entry):
    """Index catalog domains and stable IDs, without implying adoption of every type."""
    lines = [header('DOC-CAT-001', 'AutoDOC catalog reference', 'CATALOG-*/INDEX.yaml'),
             '# AutoDOC catalog reference', '',
             'Generated from the three catalog indices. These are possible documents, not completed work.', '']
    for path in paths(entry):
        data = json.loads(path.read_text(encoding='utf-8'))
        lines.extend([f'## {path.parent.name}', ''])
        if 'domains' in data:
            lines.extend(['| Domain | Purpose | Types | IDs |', '| --- | --- | ---: | --- |'])
            for domain in data['domains']:
                docs = domain['documents']
                ids = ', '.join(f'`{doc["id"]}`' for doc in docs)
                lines.append(f"| {domain['domain']} | {domain['purpose']} | {len(docs)} | {ids} |")
            lines.extend(['', f"**Total types:** {sum(len(d['documents']) for d in data['domains'])}.", ''])
        else:
            lines.extend(['| Control ID | Artifact | Purpose |', '| --- | --- | --- |'])
            for artifact in data['artifacts']:
                lines.append(f"| `{artifact['id']}` | `{artifact['path']}` | {artifact['purpose']} |")
            lines.append('')
    return '\n'.join(lines) + '\n'


def workflows(entry):
    """List workflow declarations with a hash, so any CI edit requires review."""
    lines = [header('DOC-CI-001', 'AutoDOC workflow reference', '.github/workflows/*.yml'),
             '# AutoDOC workflow reference', '',
             'Derived from workflow files. A listing or green check does not establish branch protection.', '',
             '| Workflow | Name | Jobs | Declared purpose | SHA-256 |', '| --- | --- | --- | --- | --- |']
    for path in paths(entry):
        text = path.read_text(encoding='utf-8')
        first = text.splitlines()[0].strip() if text else ''
        name = re.search(r'^name:\s*(.+)$', text, re.M)
        if not first.startswith('# ') or not name:
            raise ValueError(f'Workflow needs an initial purpose comment and name: {path}')
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        jobs_section = text.split('\njobs:\n', 1)
        if len(jobs_section) != 2:
            raise ValueError(f'Workflow missing jobs block: {path}')
        job_names = re.findall(r'^  ([A-Za-z][A-Za-z0-9_-]*):\s*$', jobs_section[1], re.M)
        if not job_names:
            raise ValueError(f'Workflow declares no jobs: {path}')
        lines.append(f'| `{path.relative_to(ROOT)}` | {name.group(1)} | {", ".join(job_names)} | {first[2:]} | `{digest}` |')
    return '\n'.join(lines) + '\n'


def outline(entry):
    lines = [header('DOC-OUT-001', 'Documentation outline', ', '.join(entry['sources'])),
             '# Documentation outline', '', 'ATX headings from configured human-owned Markdown sources.', '']
    for path in paths(entry):
        if path.read_text(encoding='utf-8').startswith('<!-- AUTO-GENERATED BY AUTODOC ENGINE.'):
            continue  # Generated targets are derived, not authoritative heading sources.
        lines.extend([f'## `{path.relative_to(ROOT)}`', ''])
        entries = headings(path)
        if path.is_relative_to(ROOT / 'TEMPLATES'):
            entries = [row for row in entries if row[1] == 1]
        for number, level, title in entries:
            lines.append(f'- L{level} line {number}: {title}')
        lines.append('')
    return '\n'.join(lines) + '\n'


def code_inventory(entry):
    lines = [header('DOC-CODE-001', 'Python code inventory', ', '.join(entry['sources'])),
             '# Python code inventory', '', 'AST-extracted Python declarations; no call graph or behavior claims.', '',
             '| Source | Line | Kind | Symbol | Signature |', '| --- | ---: | --- | --- | --- |']
    for path in paths(entry):
        module = str(path.relative_to(ROOT).with_suffix('')).replace('/', '.')
        kind_module = 'package' if path.name == '__init__.py' else 'module'
        lines.append(f'| `{path.relative_to(ROOT)}` | 1 | {kind_module} | `{module}` | — |')
        for line, kind, name, signature in python_symbols(path):
            lines.append(f'| `{path.relative_to(ROOT)}` | {line} | {kind} | `{name}` | `{signature}` |')
    return '\n'.join(lines) + '\n'


def test_inventory(entry):
    lines = [header('DOC-TEST-001', 'Test discovery inventory', ', '.join(entry['sources'])),
             '# Test discovery inventory', '', 'AST-discovered Python tests, not a report of execution or coverage.', '',
             '| File | Line | Test |', '| --- | ---: | --- |']
    for path in paths(entry):
        for line, name in python_tests(path):
            lines.append(f'| `{path.relative_to(ROOT)}` | {line} | `{name}` |')
    return '\n'.join(lines) + '\n'


def dependencies(entry):
    doc_id = 'EX-DEP-001' if entry['id'] == 'example-dependencies' else 'DOC-DEP-001'
    lines = [header(doc_id, 'Dependency declaration reference', entry['sources'][0]),
             '# Dependency declaration reference', '',
             'Declared requirements only; not an installed-dependency inventory or an SBOM.', '',
             '| Manifest | Project | Version | Group | Requirement |', '| --- | --- | --- | --- | --- |']
    for path in paths(entry):
        name, version, deps = python_dependencies(path)
        for group, requirement in deps:
            lines.append(f'| `{path.relative_to(ROOT)}` | {name} | {version} | {group} | `{requirement}` |')
        if not deps:
            lines.append(f'| `{path.relative_to(ROOT)}` | {name} | {version} | runtime | (none declared) |')
    return '\n'.join(lines) + '\n'


def completeness(entry):
    lines = [header('DOC-COV-001', 'Template and automation completeness', 'CATALOG-A/INDEX.yaml'),
             '# Template and automation completeness', '',
             'File coverage is not project adoption or compliance evidence. Template examples are synthetic.', '',
             '| Catalog domain | Types | Canonical | Blank | Example |', '| --- | ---: | ---: | ---: | ---: |']
    total = [0, 0, 0, 0]
    for catalog_name in ('CATALOG-A', 'CATALOG-B'):
        catalog_data = json.loads((ROOT / catalog_name / 'INDEX.yaml').read_text())
        for domain in catalog_data['domains']:
            docs = domain['documents']
            counts = [len(docs)] + [sum(Path(str(ROOT / d['template']) + suffix).is_file()
                                    for d in docs) for suffix in ('', '.blank', '.example')]
            total = [a + b for a, b in zip(total, counts)]
            lines.append(f'| {domain["domain"]} | ' + ' | '.join(map(str, counts)) + ' |')
    lines.extend(['', f'**Totals:** {total[0]} types; {total[1]} canonical, {total[2]} blank, '
                  f'{total[3]} synthetic example templates.', '',
                  f'**Mapped generated targets:** {len(load_map()["generated"])}. '
                  'A target can serve several types; no per-type extractor coverage is implied.', '',
                  '**Not yet implemented:** arbitrary TypeScript types, arbitrary SQL dialects, '
                  'container and monitoring inventories, signed attestations, and external audit evidence.', ''])
    return '\n'.join(lines) + '\n'



def agent_tools(entry):
    manifest = json.loads((ROOT / 'examples/ai-agent-example/src/tools.json').read_text())
    declared = manifest['tools']
    lines = [header('EX-AGENT-TOOL-001', 'Tool authorization inventory', 'examples/ai-agent-example/src/tools.json'),
             '# Tool authorization inventory', '', 'Declared local tools; not proof of LLM execution.', '',
             '| Name | Module | Function | Description |', '| --- | --- | --- | --- |']
    for tool in declared:
        if tool['module'] not in ('tools.calculator', 'tools.file_ops'):
            raise ValueError('Unsupported agent tool module: ' + tool['module'])
        path = ROOT / 'examples/ai-agent-example/src' / (tool['module'].replace('.', '/') + '.py')
        if tool['function'] not in {name for _, kind, name, _ in python_symbols(path) if kind == 'function'}:
            raise ValueError('Declared agent tool not implemented: ' + tool['function'])
        lines.append(f"| `{tool['name']}` | `{tool['module']}` | `{tool['function']}` | {tool['description']} |")
    lines.extend(['', '## Explicitly unsupported', ''])
    lines.extend('- ' + reason for reason in manifest.get('not_implemented', []))
    return '\n'.join(lines) + '\n'


def agent_prompts(entry):
    lines = [header('EX-AGENT-PROMPT-001', 'Prompt inventory', ', '.join(entry['sources'])),
             '# Prompt inventory', '', 'File names and hashes; no claim any prompt was sent to a model.', '',
             '| Path | Heading | SHA-256 |', '| --- | --- | --- |']
    for path in paths(entry):
        title = next((text for _, level, text in headings(path) if level == 1), None)
        if not title:
            raise ValueError('Prompt needs a top-level heading: ' + str(path))
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        lines.append(f'| `{path.relative_to(ROOT)}` | {title} | `{digest}` |')
    return '\n'.join(lines) + '\n'


def agent_model(entry):
    config = json.loads(paths(entry)[0].read_text())
    if set(config) != {'provider', 'mode', 'model', 'external_calls'} or (
            config['provider'] != 'none' or config['model'] is not None or
            config['external_calls'] is not False):
        raise ValueError('Unsupported example model configuration; integrate a real provider first')
    lines = [header('EX-AGENT-MODEL-001', 'Model configuration', entry['sources'][0]),
             '# Model configuration', '', 'Generated from configured values; no runtime model invocation.', '',
             '| Key | Value |', '| --- | --- |']
    for key, value in sorted(config.items()):
        lines.append(f'| {key} | `{json.dumps(value)}` |')
    return '\n'.join(lines) + '\n'




def local_tool_reference(entry):
    rows = tool_matrix(paths(entry)[0])
    lines = [header('EX-LOCAL-TOOLS-001', 'Local tool authorization', entry['sources'][0]),
             '# Local tool authorization', '',
             'Declared allowlist only; no LLM, external API or network execution.', '',
             '| Tool | Status | Risk | Confirmation | Purpose |', '| --- | --- | --- | --- | --- |']
    for row in rows:
        lines.append(f"| `{row['name']}` | {row['status']} | {row['risk']} | {row['requires_confirmation']} | {row['description']} |")
    return '\n'.join(lines) + '\n'

def environment_reference(entry):
    rows = environment(paths(entry)[0])
    lines = [header('EX-ENV-001', 'Example environment reference', entry['sources'][0]),
             '# Example environment reference', '',
             'Values are demo defaults; they are not a secret scan or proof of deployed configuration.', '',
             '| Key | Example default | Description |', '| --- | --- | --- |']
    lines.extend(f'| `{key}` | `{value}` | {description} |' for key, value, description in rows)
    return '\n'.join(lines) + '\n'


def alert_catalog(entry):
    rows = alerts(next(path for path in paths(entry) if path.name == 'alerts.yaml'), ROOT)
    lines = [header('EX-ALERT-001', 'Example alert catalog', entry['sources'][0]),
             '# Example alert catalog', '', 'Declared example alerts; no monitoring system is deployed.', '',
             '| ID | Condition | Severity | Runbook |', '| --- | --- | --- | --- |']
    for row in rows:
        lines.append(f"| `{row['id']}` | {row['condition']} | {row['severity']} | `{row['runbook']}` |")
    return '\n'.join(lines) + '\n'

def catalog_facets():
    """Partition 260 A/B type IDs into complementary development/system/product views."""
    result = {'A': [], 'B': [], 'C': []}
    system = {3, 4, 5, 6, 7, 8, 12, 13, 14, 21}
    development = {1, 2, 9, 11}
    for catalog_name in ('CATALOG-A', 'CATALOG-B'):
        for domain in json.loads((ROOT / catalog_name / 'INDEX.yaml').read_text())['domains']:
            if catalog_name == 'CATALOG-B':
                view = 'A'
            else:
                number = int(domain['domain'][1:3])
                view = 'B' if number in system else 'A' if number in development else 'C'
            result[view].append(domain)
    return result


def catalog_view(entry):
    view = entry['view']
    if view not in ('A', 'B', 'C'):
        raise ValueError('Unknown catalog view ' + view)
    label = {'A': 'Active development', 'B': 'Architecture, data and quality',
             'C': 'Operations, delivery and governance'}[view]
    lines = [header(f'DOC-CAT-VIEW-{view}', label + ' document types', 'CATALOG-A/INDEX.yaml'),
             '# ' + label + ' — catalog ' + view, '',
             'Generated crosswalk of existing stable IDs. `applies_when` is a detectable predicate '
             'evaluated against a project profile (`make docs-recommend`); `always` means every '
             'project, `assess` means no predicate exists and a human decides. A tier is an '
             'applicability suggestion, not evidence a project needs every type.', '']
    for domain in catalog_facets()[view]:
        lines += [f'## {domain["domain"]}', '', domain['purpose'] + '.', '',
                  '| Type ID | Document | Tier | Requires phase | Applies when | Purpose | Reader | When | Owner type | Mode | Maturity | Related IDs |',
                  '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |']
        for doc in domain['documents']:
            fields = [f'`{doc["id"]}`', doc['name'], doc['tier'], doc.get('phase_min') or '—',
                      ', '.join(doc['applies_when']), doc['purpose'],
                      doc.get('reader') or '—', doc['when'],
                      doc['owner_type'], doc['mode'], doc['maturity'], ', '.join(doc['related']) or '—']
            lines.append('| ' + ' | '.join(fields) + ' |')
        lines.append('')
    return '\n'.join(lines) + '\n'


def catalog_navigation(entry):
    lines = [header('DOC-CAT-NAV-001', 'Catalog navigation', 'CATALOG-A/INDEX.yaml'),
             '# Catalog navigation', '', 'Filter by phase/domain and follow the linked view. '
             'Source IDs remain in the versioned catalog indices.', '',
             '| View | Domain | Types |', '| --- | --- | ---: |']
    for view, domains in catalog_facets().items():
        for domain in domains:
            anchor = domain['domain'].lower()
            url = f'UNIVERSAL-DOCUMENT-CATALOG-{view}.md#{anchor}'
            lines.append(f'| {view} | [{domain["domain"]}]({url}) | {len(domain["documents"])} |')
    return '\n'.join(lines) + '\n'

def human_inventory(entry):
    rows = []
    for path in controlled():
        fields = parse_frontmatter(path)
        if fields['auto_generated'] == 'false':
            rows.append({'id': fields['id'], 'path': str(path.relative_to(ROOT)),
                         'type': fields['type'], 'owner': fields['owner'], 'status': fields['status'],
                         'last_reviewed': fields['last_reviewed'], 'next_review': fields['next_review'],
                         'classification': fields['classification'], 'applies_to': []})
    return json.dumps({'version': 1, 'source': 'controlled Markdown frontmatter',
                       'note': 'AUTO-GENERATED; do not edit. Project applicability is not inferred.',
                       'documents': rows}, indent=2) + '\n'


def relationship_graph(entry):
    edges = []
    for path in controlled():
        fields = parse_frontmatter(path)
        related = json.loads(fields['related'])
        for target in related:
            edges.append({'from': fields['id'], 'to': target, 'kind': 'related'})
        if fields['supersedes'] != 'null':
            edges.append({'from': fields['id'], 'to': fields['supersedes'], 'kind': 'supersedes'})
    return json.dumps({'version': 1, 'source': 'frontmatter related/supersedes',
                       'note': 'AUTO-GENERATED; semantics require human review.',
                       'edges': sorted(edges, key=lambda e: (e['from'], e['kind'], e['to']))}, indent=2) + '\n'

def master_index(entry):
    records = []
    for path in controlled():
        fields = parse_frontmatter(path)
        records.append({'id': fields['id'], 'path': str(path.relative_to(ROOT)), 'owner': fields['owner'],
                        'status': fields['status'], 'type': fields['type'], 'last_reviewed': fields['last_reviewed']})
    return json.dumps({'version': 1, 'documents': records}, indent=2) + '\n'


def check_supersedes_cycles(links):
    """A supersession chain must terminate (related links may intentionally be cyclic)."""
    for source in links:
        visited = set()
        current = source
        while current in links:
            if current in visited:
                raise ValueError('Circular supersedes chain starting at ' + source)
            visited.add(current)
            current = links[current]


def relationship_visualization(entry):
    """Mermaid of real frontmatter and mapped source relationships only."""
    links = []
    for path in controlled():
        meta = parse_frontmatter(path)
        for related in json.loads(meta['related']):
            links.append((meta['id'], related, 'related'))
        if meta['supersedes'] != 'null':
            links.append((meta['id'], meta['supersedes'], 'supersedes'))
    check_supersedes_cycles({a: b for a, b, kind in links if kind == 'supersedes'})
    for mapping in load_map()['generated']:
        for source in mapping['sources']:
            links.append((source, mapping['target'], 'generates'))
    for catalog_name in ('CATALOG-A', 'CATALOG-B'):
        catalog_data = json.loads((ROOT / catalog_name / 'INDEX.yaml').read_text())
        for domain in catalog_data['domains']:
            for doc in domain['documents']:
                links.extend((doc['id'], doc['template'] + suffix, 'template') for suffix in ('', '.blank', '.example'))
    import hashlib
    nodes = sorted({node for a, b, _ in links for node in (a, b)})
    ids = {node: 'n' + hashlib.sha256(node.encode()).hexdigest()[:16] for node in nodes}
    lines = [header('DOC-REL-001', 'Mapped document relationships', 'docs/.doc-sync-map.yaml'),
             '# Mapped document relationships', '',
             'Directed links are derived from frontmatter, mapped generators and catalog templates. '
             'Absence of an edge is not evidence of independence. All controlled docs are indexed by the master index.', '',
             '```mermaid', 'flowchart LR']
    for node in nodes:
        safe = node.replace('"', "'").replace('|', '/')
        lines.append(f'    {ids[node]}["{safe}"]')
    for a, b, kind in sorted(set(links)):
        lines.append(f'    {ids[a]} -->|{kind}| {ids[b]}')
    lines += ['```', '']
    return '\n'.join(lines) + '\n'

GENERATORS = {'api': api, 'config': config, 'env': env, 'sql': sql, 'automation': automation,
              'master_index': master_index, 'catalog': catalog, 'workflows': workflows,
              'outline': outline, 'code_inventory': code_inventory, 'test_inventory': test_inventory,
              'dependencies': dependencies, 'completeness': completeness,
              'human_inventory': human_inventory, 'relationship_graph': relationship_graph,
              'agent_tools': agent_tools, 'agent_prompts': agent_prompts, 'agent_model': agent_model,
              'catalog_view': catalog_view, 'catalog_navigation': catalog_navigation,
              'environment_reference': environment_reference, 'alert_catalog': alert_catalog,
              'local_tool_reference': local_tool_reference,
              'relationship_visualization': relationship_visualization}


def generate(check=False, only=None, findings=None):
    failures = []
    entries = load_map()['generated']
    if only and only not in {entry['id'] for entry in entries}:
        raise ValueError('Unknown generator ID: ' + only)
    for entry in entries:
        if only and entry['id'] != only:
            continue
        target = safe_path(entry['target'])
        expected = GENERATORS[entry['generator']](entry)
        if target.suffix == '.md':
            expected = expected.rstrip('\n') + '\n'
        if target.exists() and target.read_text(encoding='utf-8') == expected:
            continue
        if check:
            failures.append(f"{entry['target']} (sources: {', '.join(entry['sources'])}); run make docs:generate")
            if findings is not None:
                findings.append({'rule': 'drift', 'location': entry['target'],
                                 'detail': f"generated from {', '.join(entry['sources'])}",
                                 'fix': 'run make docs:generate'})
        else:
            if target.suffix == '.md' and target.exists() and not target.read_text(encoding='utf-8').startswith(
                    '<!-- AUTO-GENERATED BY AUTODOC ENGINE.'):
                raise ValueError('Refusing to overwrite unmarked Markdown target: ' + entry['target'])
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(expected, encoding='utf-8')
            print('Updated', entry['target'])
    if failures:
        print('Generated documentation drift:\n' + '\n'.join(failures), file=sys.stderr)
    return not failures


def git(*args):
    return subprocess.check_output(['git', *args], cwd=ROOT, text=True).strip()


def changed(base=None, staged=False):
    if base:
        result = git('diff', '--name-only', '--diff-filter=ACMRT', base + '...HEAD')
    else:
        result = git('diff', '--cached' if staged else 'HEAD', '--name-only', '--diff-filter=ACMRT')
    return set(result.splitlines()) if result else set()


def matches(file, pattern):
    return fnmatch.fnmatchcase(file, pattern) or (pattern.endswith('/**') and file.startswith(pattern[:-3]))


def impact(base=None, staged=False):
    files = changed(base, staged)
    data = load_map()
    failures = []
    for rule in data['review']:
        sources = [f for f in files if any(matches(f, p) for p in rule['sources'])]
        if sources and not any(t in files for t in rule['targets']):
            message = f"{rule['id']}: changed {', '.join(sorted(sources))}; review {', '.join(rule['targets'])}"
            if rule['level'] == 'block':
                failures.append(message)
            else:
                print('WARNING:', message)
    changelog = data.get('changelog')
    if changelog and any(any(matches(f, p) for p in changelog['sources']) for f in files):
        if changelog['target'] not in files:
            failures.append('User-facing change requires ' + changelog['target'])
    living = data['living']
    if any(any(matches(f, p) for p in living['sources']) for f in files):
        missing = [t for t in living['targets'] if t not in files]
        if missing:
            failures.append('Living state not updated: ' + ', '.join(missing))
    if failures:
        print('\n'.join(failures), file=sys.stderr)
    return not failures


def parse_frontmatter(path):
    return parse_frontmatter_text(path.read_text(encoding='utf-8'))


def parse_frontmatter_text(text):
    if text.startswith('<!-- AUTO-GENERATED BY AUTODOC ENGINE. '):
        text = text.split('\n', 1)[1]
    if not text.startswith('---\n') or '\n---\n' not in text[4:]:
        raise ValueError('missing YAML frontmatter')
    section = text.split('\n---\n', 1)[0][4:]
    # Constrained YAML subset: one scalar or inline list per key; no nested mappings.
    fields = {}
    for line in section.splitlines():
        if not re.match(r'^[a-z_]+: ', line):
            raise ValueError('invalid metadata line: ' + line)
        key, value = line.split(': ', 1)
        if key in fields:
            raise ValueError('duplicate metadata key: ' + key)
        fields[key] = value.strip().strip('"')
    return fields


def controlled():
    paths_ = list((ROOT / 'docs').rglob('*.md')) + list((ROOT / 'CONTROL').rglob('*.md'))
    paths_ += list((ROOT / 'EXAMPLE-PROJECT/docs').rglob('*.md'))
    paths_ += list((ROOT / 'examples/ai-agent-example/docs').rglob('*.md'))
    paths_ += list((ROOT / 'examples/local-tools-example/docs').rglob('*.md'))
    paths_ += [ROOT / name for name in ('CURRENT-STATE.md', 'NEXT-ACTION.md', 'RECENT-CHANGES.md',
                                       'AGENTS.md', 'CLAUDE.md', 'AGENT-MEMORY.md',
                                       'ANTI-PATTERNS-FOR-AGENT.md', 'CONTEXT-SNAPSHOT.md',
                                       'TASK-FOR-AGENT.md')]
    return sorted(set(paths_))



def validate_staged():
    """Read Git index blobs, not potentially different worktree copies, for staged metadata."""
    changed_files = git('diff', '--cached', '--name-only', '--diff-filter=ACMRT').splitlines()
    controlled_roots = {'CURRENT-STATE.md', 'NEXT-ACTION.md', 'RECENT-CHANGES.md',
                        'AGENTS.md', 'CLAUDE.md', 'AGENT-MEMORY.md',
                        'ANTI-PATTERNS-FOR-AGENT.md', 'CONTEXT-SNAPSHOT.md', 'TASK-FOR-AGENT.md'}
    controlled_dirs = ('docs/', 'CONTROL/', 'EXAMPLE-PROJECT/docs/',
                       'examples/ai-agent-example/docs/', 'examples/local-tools-example/docs/')
    schema = json.loads((ROOT / 'CONTROL/metadata/FRONT-MATTER-SCHEMA.json').read_text())
    errors = []
    for name in changed_files:
        if not name.endswith('.md') or not (name in controlled_roots or name.startswith(controlled_dirs)):
            continue
        try:
            text = subprocess.check_output(['git', 'show', ':' + name], cwd=ROOT, text=True)
            meta = parse_frontmatter_text(text)
            missing = [key for key in schema['required'] if not meta.get(key)]
            if missing:
                raise ValueError('missing staged metadata: ' + ', '.join(missing))
            if set(meta) - set(schema['properties']):
                raise ValueError('unknown staged metadata keys')
            for key, spec in schema['properties'].items():
                if 'enum' in spec and meta[key] not in spec['enum']:
                    raise ValueError('invalid staged ' + key + ': ' + meta[key])
            for key in ('last_verified', 'last_reviewed', 'last_updated', 'effective_date', 'next_review'):
                date.fromisoformat(meta[key])
            if meta['auto_generated'] not in ('true', 'false') or (
                    meta['auto_generated'] == 'true') != text.startswith(
                    '<!-- AUTO-GENERATED BY AUTODOC ENGINE. '):
                raise ValueError('staged generated marker and auto_generated disagree')
        except (ValueError, KeyError, subprocess.CalledProcessError) as exc:
            errors.append(name + ': ' + str(exc))
    for error in errors:
        print(error, file=sys.stderr)
    return not errors

def validate(freshness=False, now=None, findings=None):
    schema_path = ROOT / 'CONTROL/metadata/FRONT-MATTER-SCHEMA.json'
    if not schema_path.is_file():
        # A repository that has not adopted AutoDOC's metadata has no review dates to read, so
        # there is nothing here to validate. enforce.py reports that freshness could not run
        # rather than letting the absence look like a clean result.
        return True
    schema = json.loads(schema_path.read_text())
    required = schema['required']
    seen, errors, relationships, supersedes = set(), [], [], {}
    today = now or date.today()
    for path in controlled():
        relative = str(path.relative_to(ROOT))
        try:
            fields = parse_frontmatter(path)
            missing = [key for key in required if not fields.get(key)]
            if missing:
                raise ValueError('missing: ' + ', '.join(missing))
            if fields['id'] in seen:
                raise ValueError('duplicate id: ' + fields['id'])
            seen.add(fields['id'])
            extra = set(fields) - set(schema['properties'])
            if extra:
                raise ValueError('unknown metadata keys: ' + ', '.join(sorted(extra)))
            for key, spec in schema['properties'].items():
                if 'enum' in spec and fields[key] not in spec['enum']:
                    raise ValueError('invalid ' + key + ': ' + fields[key])
            for key in ('last_verified', 'last_reviewed', 'last_updated', 'effective_date', 'next_review'):
                date.fromisoformat(fields[key])
            if date.fromisoformat(fields['next_review']) < date.fromisoformat(fields['last_verified']):
                raise ValueError('next_review before last_verified')
            if not fields['owner'].startswith('@') or not fields['reviewer'].startswith('@'):
                raise ValueError('owner and reviewer must identify a person or team')
            try:
                related = json.loads(fields['related'])
            except json.JSONDecodeError as exc:
                raise ValueError('related must be a JSON-compatible YAML list') from exc
            if not isinstance(related, list) or not all(isinstance(id_, str) for id_ in related):
                raise ValueError('related must be a list of document IDs')
            relationships.append((relative, related + ([] if fields['supersedes'] == 'null' else [fields['supersedes']])))
            if fields['supersedes'] != 'null':
                supersedes[fields['id']] = fields['supersedes']
            if fields['auto_generated'] == 'true' and fields['source_of_truth'] == 'human':
                raise ValueError('generated document needs a source of truth')
            days = int(fields['review_days'])
            if days < 1:
                raise ValueError('review_days must be positive')
            due = min(date.fromisoformat(fields['next_review']),
                      date.fromisoformat(fields['last_verified']) + timedelta(days=days))
            if freshness and fields['auto_generated'] != 'true' and today > due:
                msg = 'overdue review (critical)' if fields['criticality'] == 'critical' else 'overdue review (warning)'
                if findings is not None:
                    critical = fields['criticality'] == 'critical'
                    findings.append({'rule': 'freshness.critical' if critical else 'freshness.review',
                                     'location': relative, 'detail': msg,
                                     'fix': 'review the document, or change review_days with a reason'})
                if fields['criticality'] == 'critical':
                    errors.append(relative + ': ' + msg)
                else:
                    print('WARNING:', relative + ': ' + msg)
            if fields['auto_generated'] not in ('true', 'false'):
                raise ValueError('auto_generated must be true or false')
            marked = path.read_text(encoding='utf-8').startswith('<!-- AUTO-GENERATED BY AUTODOC ENGINE. ')
            if (fields['auto_generated'] == 'true') != marked:
                raise ValueError('generated marker and auto_generated disagree')
        except (ValueError, KeyError) as error:
            errors.append(relative + ': ' + str(error))
    for path, ids in relationships:
        for id_ in ids:
            if id_ not in seen:
                errors.append(path + ': unknown related/superseded document ID ' + id_)
    try:
        check_supersedes_cycles(supersedes)
    except ValueError as exc:
        errors.append(str(exc))
    for error in errors:
        print(error, file=sys.stderr)
    return not errors




def replace_block(text, body):
    start, end = '<!-- auto:start -->', '<!-- auto:end -->'
    if (start in text) != (end in text):
        raise ValueError('Incomplete state block; repair both auto markers')
    if start not in text:
        return text.rstrip() + '\n\n' + start + '\n' + body + '\n' + end + '\n'
    return text.split(start)[0] + start + '\n' + body + '\n' + end + text.split(end, 1)[1]


def update_state(base=None, staged=False):
    """Update observable blocks only; preserve manually reviewed context and next action."""
    files = sorted(changed(base, staged) - {'CURRENT-STATE.md', 'NEXT-ACTION.md', 'RECENT-CHANGES.md'})
    if staged and not files:
        return
    log = git('log', '-20', '--format=%h %ad %s', '--date=short').splitlines()
    docs = [parse_frontmatter(p) for p in controlled()]
    generated = sum(d['auto_generated'] == 'true' for d in docs)
    overdue = sum(d['auto_generated'] == 'false' and
                  date.today() > min(date.fromisoformat(d['next_review']),
                                     date.fromisoformat(d['last_verified']) + timedelta(days=int(d['review_days'])))
                  for d in docs)
    cat_count = sum(len(domain['documents']) for catalog in ('CATALOG-A', 'CATALOG-B')
                    for domain in json.loads((ROOT / catalog / 'INDEX.yaml').read_text())['domains'])
    stats = (f'- Catalog types: {cat_count} (not necessarily instantiated).\n'
             f'- Controlled docs: {len(docs)} ({generated} generated, {len(docs)-generated} human-owned).\n'
             f'- Overdue human-owned docs: {overdue}.\n'
             '- Open gaps: see `docs/00-governance/ENGINE-COVERAGE.md`; this block does not infer intent.')
    paths = '\n'.join('- `' + name + '`' for name in files[:20]) or '- None staged or changed.'
    if len(files) > 20:
        paths += f'\n- … and {len(files) - 20} more; use git diff --cached --name-only.'
    recent = ('## Last 20 Git commits\n\n' + ('\n'.join('- ' + line for line in log) or '- No commits.') +
              '\n\n## Changed paths at update time\n\n' + paths)
    for name, body in (('CURRENT-STATE.md', stats), ('RECENT-CHANGES.md', recent)):
        path = ROOT / name
        text = path.read_text(encoding='utf-8')
        result = replace_block(text, body)
        if text != result:
            path.write_text(result, encoding='utf-8')
            print('Updated', name, '(review and stage explicitly)')

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('command', choices=['generate', 'drift', 'impact', 'validate', 'freshness', 'state'])
    parser.add_argument('--base', help='Git merge base/ref for PR comparisons')
    parser.add_argument('--staged', action='store_true')
    parser.add_argument('--only', help='Only one mapped generated entry ID')
    parser.add_argument('--check', action='store_true', help='Check instead of writing (generate only)')
    parser.add_argument('--write', action='store_true', help='Explicit write mode (generate only)')
    args = parser.parse_args()
    try:
        if args.command == 'generate':
            if args.check and args.write:
                parser.error('--check and --write are mutually exclusive')
            ok = generate(check=args.check, only=args.only)
        elif args.command == 'drift':
            ok = generate(check=True)
        elif args.command == 'impact':
            ok = impact(args.base, args.staged)
        elif args.command == 'state':
            update_state(args.base, args.staged)
            ok = True
        else:
            ok = validate(freshness=args.command == 'freshness')
        sys.exit(0 if ok else 1)
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        print('AutoDOC error:', error, file=sys.stderr)
        sys.exit(2)


if __name__ == '__main__':
    main()
