#!/usr/bin/env python3
"""Reject approved human documents with no section or content beyond their title.

An index placeholder is not a document. Generated targets are excluded because byte
drift, not prose volume, is what validates them; a short generated table can be correct.
Draft stubs warn instead of failing, because a draft scaffold is an honest intermediate state.
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'scripts/doc-sync'))
from engine import controlled, parse_frontmatter  # noqa: E402

GENERATED_MARKER = '<!-- AUTO-GENERATED BY AUTODOC ENGINE.'
SECTION = re.compile(r'^#{2,6}\s')
BOILER = re.compile(r'^\*\*(?:Purpose|Automation Rule):?\*\*')
PLACEHOLDER = re.compile(r'\[Fill in|<!-- Fill in|REPLACE-WITH|@assign-')
SKIP_PREFIX = ('#', '<!--', '>', '|', '```', '~~~', '---')


def substance(text):
    """Return (section headings, content words) for a controlled Markdown body.

    Frontmatter, the generated marker, the title, index Purpose/Automation-Rule
    boilerplate, placeholders, blockquotes, tables, code fences and comments are not
    evidence of content.
    """
    if text.startswith(GENERATED_MARKER):
        text = text.split('\n', 1)[1]
    body = text.split('\n---\n', 1)[1] if text.startswith('---\n') else text
    sections, lines = 0, []
    for raw in body.splitlines():
        line = raw.strip()
        if SECTION.match(line):
            sections += 1
            continue
        if not line or line.startswith(SKIP_PREFIX):
            continue
        if BOILER.match(line) or PLACEHOLDER.search(line):
            continue
        lines.append(line)
    return sections, len(' '.join(lines).split())


def scan():
    """Return (approved_stubs, draft_stubs) as sorted relative path lists."""
    approved, draft = [], []
    for path in controlled():
        fields = parse_frontmatter(path)
        if fields['auto_generated'] == 'true':
            continue  # derived documents are checked by byte drift against their sources
        sections, words = substance(path.read_text(encoding='utf-8'))
        if sections or words:
            continue
        relative = str(path.relative_to(ROOT))
        (approved if fields['status'] == 'approved' else draft).append(relative)
    return sorted(approved), sorted(draft)


def collect():
    """Return placeholder findings as dicts: an approved stub and a draft placeholder differ.

    An approved document with no content is a broken promise (`stubs`); a draft that is still a
    placeholder is unfilled scaffold (`placeholders`). The phase decides how hard each fails.
    """
    approved, draft = scan()
    findings = [{'rule': 'placeholders', 'location': path,
                 'detail': 'draft has no content beyond its title',
                 'fix': 'write it, or remove the placeholder'} for path in draft]
    findings += [{'rule': 'stubs', 'location': path,
                  'detail': 'approved document has no content beyond its title',
                  'fix': 'write it, return it to draft, or remove it'} for path in approved]
    return findings


def check():
    approved, draft = scan()
    for path in draft:
        print(f'WARNING: {path}: draft has no section or content beyond its title; '
              'add content or remove the placeholder', file=sys.stderr)
    for path in approved:
        print(f'{path}: approved document has no section or content beyond its title; '
              'write it, return it to draft, or remove it', file=sys.stderr)
    if approved:
        print(f'Approved stub documents: {len(approved)} (a placeholder index is not a document)',
              file=sys.stderr)
    return not approved


if __name__ == '__main__':
    argparse.ArgumentParser(description=__doc__).parse_args()
    raise SystemExit(0 if check() else 1)
